"""phase_14_portrait_cat_portraits

Revision ID: 198e1f71f53e
Revises: f3782b65138a
Create Date: 2026-08-16 01:19:40.104394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '198e1f71f53e'
down_revision: Union[str, None] = 'f3782b65138a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cat_portraits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('style_id', sa.String(length=30), nullable=False),
    sa.Column('customization', sa.String(length=120), nullable=True),
    sa.Column('generation_identity_hash', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('error_code', sa.String(length=40), nullable=True),
    sa.Column('error_message', sa.String(length=300), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['cat_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cat_portraits_analysis_id'), 'cat_portraits', ['analysis_id'], unique=False)
    op.create_index('ix_cat_portraits_analysis_id_created_at', 'cat_portraits', ['analysis_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_cat_portraits_generation_identity_hash'), 'cat_portraits', ['generation_identity_hash'], unique=False)
    op.create_index('ix_cat_portraits_identity_hash', 'cat_portraits', ['analysis_id', 'generation_identity_hash', 'status'], unique=False)
    op.create_index('ix_cat_portraits_user_id', 'cat_portraits', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cat_portraits_user_id', table_name='cat_portraits')
    op.drop_index('ix_cat_portraits_identity_hash', table_name='cat_portraits')
    op.drop_index(op.f('ix_cat_portraits_generation_identity_hash'), table_name='cat_portraits')
    op.drop_index('ix_cat_portraits_analysis_id_created_at', table_name='cat_portraits')
    op.drop_index(op.f('ix_cat_portraits_analysis_id'), table_name='cat_portraits')
    op.drop_table('cat_portraits')
    # ### end Alembic commands ###
