"""phase 10 gamification: user_progress and collection_events

Revision ID: 376d7d0d1186
Revises: b04f6df3d75b
Create Date: 2026-08-11 22:51:38.988908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '376d7d0d1186'
down_revision: Union[str, None] = 'b04f6df3d75b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('xp_awarded', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_type', 'target_id', name='uq_collection_event')
    )
    op.create_index(op.f('ix_collection_events_user_id'), 'collection_events', ['user_id'], unique=False)
    op.create_index('ix_collection_events_user_id_event_type', 'collection_events', ['user_id', 'event_type'], unique=False)
    op.create_table('user_progress',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('xp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_progress')
    op.drop_index('ix_collection_events_user_id_event_type', table_name='collection_events')
    op.drop_index(op.f('ix_collection_events_user_id'), table_name='collection_events')
    op.drop_table('collection_events')
    # ### end Alembic commands ###
