"""phase_15_explore_public_indexes

Revision ID: 47eb5d38195f
Revises: 198e1f71f53e
Create Date: 2026-08-16 14:12:32.488773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '47eb5d38195f'
down_revision: Union[str, None] = '198e1f71f53e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_cat_analyses_is_public_breed_label', 'cat_analyses', ['is_public', 'breed_label'], unique=False)
    op.create_index('ix_cat_analyses_is_public_created_at', 'cat_analyses', ['is_public', 'created_at'], unique=False)
    op.create_index('ix_cat_analyses_is_public_rarity', 'cat_analyses', ['is_public', 'rarity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cat_analyses_is_public_rarity', table_name='cat_analyses')
    op.drop_index('ix_cat_analyses_is_public_created_at', table_name='cat_analyses')
    op.drop_index('ix_cat_analyses_is_public_breed_label', table_name='cat_analyses')
    # ### end Alembic commands ###
