"""phase 12 explainability: cat_explanations

Revision ID: 883a3ad9af8c
Revises: 8903bf7a8de1
Create Date: 2026-08-15 11:12:30.038636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '883a3ad9af8c'
down_revision: Union[str, None] = '8903bf7a8de1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cat_explanations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('method', sa.String(length=30), server_default='grad-cam', nullable=False),
    sa.Column('target_layer', sa.String(length=50), nullable=False),
    sa.Column('target_class', sa.String(length=60), nullable=False),
    sa.Column('target_class_index', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('breed_model_version', sa.String(length=20), nullable=False),
    sa.Column('heatmap_url', sa.String(length=500), nullable=True),
    sa.Column('overlay_url', sa.String(length=500), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=False),
    sa.Column('image_height', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['cat_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id', 'target_class', 'breed_model_version', name='uq_cat_explanation_cache_key')
    )
    op.create_index(op.f('ix_cat_explanations_analysis_id'), 'cat_explanations', ['analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cat_explanations_analysis_id'), table_name='cat_explanations')
    op.drop_table('cat_explanations')
    # ### end Alembic commands ###
