"""phase 11 similarity: cat_embeddings

Revision ID: 8903bf7a8de1
Revises: 376d7d0d1186
Create Date: 2026-08-12 13:12:12.961992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8903bf7a8de1'
down_revision: Union[str, None] = '376d7d0d1186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cat_embeddings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('vector_id', sa.BigInteger(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding_model', sa.String(length=50), nullable=False),
    sa.Column('embedding_version', sa.String(length=20), nullable=False),
    sa.Column('embedding_dim', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['cat_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cat_embeddings_analysis_id'), 'cat_embeddings', ['analysis_id'], unique=True)
    op.create_index(op.f('ix_cat_embeddings_content_hash'), 'cat_embeddings', ['content_hash'], unique=False)
    op.create_index(op.f('ix_cat_embeddings_vector_id'), 'cat_embeddings', ['vector_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cat_embeddings_vector_id'), table_name='cat_embeddings')
    op.drop_index(op.f('ix_cat_embeddings_content_hash'), table_name='cat_embeddings')
    op.drop_index(op.f('ix_cat_embeddings_analysis_id'), table_name='cat_embeddings')
    op.drop_table('cat_embeddings')
    # ### end Alembic commands ###
