"""add cat_analyses and stories tables

Revision ID: d64228515183
Revises: 
Create Date: 2026-08-10 00:59:14.083132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd64228515183'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cat_analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('breed_label', sa.String(length=100), nullable=False),
    sa.Column('breed_confidence', sa.Float(), nullable=False),
    sa.Column('breed_mode', sa.String(length=20), nullable=False),
    sa.Column('colors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('colors_mode', sa.String(length=20), nullable=False),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('profile_mode', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('style', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('story', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('story_mode', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['cat_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_analysis_id'), 'stories', ['analysis_id'], unique=False)
    op.create_index('ix_stories_analysis_id_style', 'stories', ['analysis_id', 'style'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stories_analysis_id_style', table_name='stories')
    op.drop_index(op.f('ix_stories_analysis_id'), table_name='stories')
    op.drop_table('stories')
    op.drop_table('cat_analyses')
    # ### end Alembic commands ###
