"""add is_public to cat_analyses

Revision ID: d64ea3d2f0bd
Revises: d64228515183
Create Date: 2026-08-11 13:16:16.940449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd64ea3d2f0bd'
down_revision: Union[str, None] = 'd64228515183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cat_analyses', sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cat_analyses', 'is_public')
    # ### end Alembic commands ###
