"""phase 13 personality: cat_personalities and personality_interpretations

Revision ID: f3782b65138a
Revises: 883a3ad9af8c
Create Date: 2026-08-15 23:38:02.886224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f3782b65138a'
down_revision: Union[str, None] = '883a3ad9af8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cat_personalities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('personality_engine_version', sa.String(length=20), nullable=False),
    sa.Column('archetype_id', sa.String(length=40), nullable=False),
    sa.Column('traits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['cat_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id', 'personality_engine_version', name='uq_cat_personality_cache_key')
    )
    op.create_index(op.f('ix_cat_personalities_analysis_id'), 'cat_personalities', ['analysis_id'], unique=False)
    op.create_table('personality_interpretations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('personality_id', sa.Uuid(), nullable=False),
    sa.Column('interpretation_mode', sa.String(length=20), nullable=False),
    sa.Column('interpretation_model', sa.String(length=30), nullable=True),
    sa.Column('interpretation_version', sa.String(length=20), nullable=False),
    sa.Column('headline', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=False),
    sa.Column('catchphrase', sa.String(length=140), nullable=False),
    sa.Column('secret_talent', sa.String(length=140), nullable=False),
    sa.Column('fictional_job', sa.String(length=100), nullable=False),
    sa.Column('fun_fact', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['personality_id'], ['cat_personalities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_personality_interpretations_personality_id', 'personality_interpretations', ['personality_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_personality_interpretations_personality_id', table_name='personality_interpretations')
    op.drop_table('personality_interpretations')
    op.drop_index(op.f('ix_cat_personalities_analysis_id'), table_name='cat_personalities')
    op.drop_table('cat_personalities')
    # ### end Alembic commands ###
